version: '3.9'

services:
  frontend:
    build:
      context: ./email-visualizer
    ports:
      - "8081:8080"
    container_name: visualizer
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: server
    depends_on:
      - db

  db:
    build:
      context: ./zincsearch-server
    ports:
      - "4080:4080"
    container_name: zincsearch-server
    volumes:
      - ./zincsearch/data:/data
