version: '3'

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=${ZINC_FIRST_ADMIN_USER}
      - ZINC_FIRST_ADMIN_PASSWORD=${ZINC_FIRST_ADMIN_PASSWORD}
    ports:
      - '8081:4080'
    volumes:
      - ./zinc:/var/lib/zinc
    networks:
      - common_network

  backend:
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        ZINC_FIRST_ADMIN_USER: $ZINC_FIRST_ADMIN_USER
        ZINC_FIRST_ADMIN_PASSWORD: $ZINC_FIRST_ADMIN_PASSWORD
        ZINC_SERVER_URL: $ZINC_SERVER_URL
    ports:
      - 8000:8081
    depends_on:
      - zincsearch

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    environment:
      - API_HOST=http://backend:3000
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - common_network

networks:
  common_network:
    driver: bridge
